window.ALL_PROPERTIES = [
    {
        "category": "house",
        "code": "P-001",
        "title": "Luxury Villa with Ocean View",
        "price": 45000000,
        "currency": "LKR",
        "location": {
            "city": "Colombo 03",
            "area": "Kollupitiya",
            "district": "Colombo"
        },
        "bedrooms": 4,
        "bathrooms": 3,
        "areaSize": 3500,
        "areaUnit": "sqft",
        "floors": 2,
        "listingType": "sale",
        "condition": "new",
        "status": "available",
        "electricity": true,
        "water": true,
        "description": "Experience luxury living in this stunning 4-bedroom villa offering breathtaking ocean views. Features a modern open-plan kitchen, spacious living areas, and a private garden. Located in the heart of Colombo 03, close to all amenities.",
        "features": ["Ocean View", "Garden", "Garage", "Air Conditioning", "Modern Kitchen"],
        "images": ["https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800"],
        "featured": true
    },
    {
        "category": "house",
        "code": "P-002",
        "title": "Modern Apartment in City Center",
        "price": 150000,
        "currency": "LKR",
        "location": {
            "city": "Colombo 07",
            "area": "Cinnamon Gardens",
            "district": "Colombo"
        },
        "bedrooms": 2,
        "bathrooms": 2,
        "areaSize": 1200,
        "areaUnit": "sqft",
        "floors": 1,
        "listingType": "rent",
        "condition": "used",
        "status": "available",
        "description": "A stylish and fully furnished 2-bedroom apartment available for rent in the prestigious Cinnamon Gardens area. Amenities include a rooftop pool, gym, and 24/7 security.",
        "features": ["Swimming Pool", "Gym", "Furnished", "24/7 Security", "Balcony"],
        "images": ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1515263487990-61b07816b324?auto=format&fit=crop&q=80&w=800"],
        "featured": false
    },
    {
        "category": "house",
        "code": "P-003",
        "title": "Cozy Family House",
        "price": 28000000,
        "currency": "LKR",
        "location": {
            "city": "Nugegoda",
            "area": "Jubilee Post",
            "district": "Colombo"
        },
        "bedrooms": 3,
        "bathrooms": 2,
        "areaSize": 2000,
        "areaUnit": "sqft",
        "floors": 1,
        "listingType": "sale",
        "condition": "used",
        "status": "sold",
        "description": "Charming single-story house perfect for a family. Located in a quiet residential neighborhood in Nugegoda. Features a large backyard and easy access to schools and supermarkets.",
        "features": ["Large Garden", "Quiet Neighborhood", "Single Story", "Car Port"],
        "images": ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1599809275372-b40c7e9379d5?auto=format&fit=crop&q=80&w=800"],
        "featured": false
    },
    {
        "category": "house",
        "code": "P-004",
        "title": "Commercial Space for Rent",
        "price": 250000,
        "currency": "LKR",
        "location": {
            "city": "Dehiwala",
            "area": "Hill Street",
            "district": "Colombo"
        },
        "bedrooms": 0,
        "bathrooms": 1,
        "areaSize": 1500,
        "areaUnit": "sqft",
        "floors": 1,
        "listingType": "rent",
        "condition": "used",
        "status": "available",
        "description": "Spacious commercial space ideal for an office or retail outlet. Located on the main road with high visibility and parking availability.",
        "features": ["Main Road", "Parking", "High Visibility", "Office Space"],
        "images": ["https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800"],
        "featured": false
    },
    {
        "category": "house",
        "code": "P-005",
        "title": "Brand New Luxury Apartment",
        "price": 55000000,
        "currency": "LKR",
        "location": {
            "city": "Rajagiriya",
            "area": "Buthgamuwa",
            "district": "Colombo"
        },
        "bedrooms": 3,
        "bathrooms": 3,
        "areaSize": 1800,
        "areaUnit": "sqft",
        "floors": 8,
        "listingType": "sale",
        "condition": "new",
        "status": "reserved",
        "description": "Brand new 3-bedroom apartment with ultra-modern finishes. The building offers premium facilities including a clubhouse, infinity pool, and jogging track.",
        "features": ["Brand New", "Infinity Pool", "Clubhouse", "Jogging Track", "Maid's Room"],
        "images": ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800"],
        "featured": true
    },
    {
        "category": "house",
        "code": "P-006",
        "title": "Colonial Bungalow",
        "price": 85000000,
        "currency": "LKR",
        "location": {
            "city": "Mount Lavinia",
            "area": "Hotel Road",
            "district": "Colombo"
        },
        "bedrooms": 5,
        "bathrooms": 4,
        "areaSize": 4500,
        "areaUnit": "sqft",
        "floors": 2,
        "listingType": "sale",
        "condition": "used",
        "status": "available",
        "description": "Historic colonial-style bungalow with extensive grounds. Needs some renovation but offers unique architectural character and huge potential. Walking distance to the beach.",
        "features": ["Historic", "Large Land", "Near Beach", "Renovation Project", "High Ceilings"],
        "images": ["https://images.unsplash.com/photo-1600596542815-22b8915252d7?auto=format&fit=crop&q=80&w=800"],
        "featured": true
    },
    {
        "category": "house",
        "code": "P-007",
        "title": "Seaside Cabana Resort",
        "price": 65000000,
        "currency": "LKR",
        "location": {
            "city": "Hikkaduwa",
            "area": "Beach Road",
            "district": "Galle"
        },
        "bedrooms": 8,
        "bathrooms": 8,
        "areaSize": 5000,
        "areaUnit": "sqft",
        "floors": 1,
        "listingType": "sale",
        "condition": "used",
        "status": "available",
        "description": "A fully operational boutique resort with 8 cabanas right on Hikkaduwa beach. Excellent investment opportunity with high ROI.",
        "features": ["Beachfront", "Commercial License", "Restaurant", "Garden"],
        "images": ["https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&q=80&w=800"],
        "featured": true
    },
    {
        "category": "house",
        "code": "P-008",
        "title": "Budget City Apartment",
        "price": 85000,
        "currency": "LKR",
        "location": {
            "city": "Colombo 05",
            "area": "Kirulapone",
            "district": "Colombo"
        },
        "bedrooms": 2,
        "bathrooms": 1,
        "areaSize": 900,
        "areaUnit": "sqft",
        "floors": 3,
        "listingType": "rent",
        "condition": "used",
        "status": "available",
        "description": "Affordable 2-bedroom apartment in a convenient location. Close to bus routes and markets. Ideal for students or small families.",
        "features": ["Close to Transport", "Balcony", " unfurnished"],
        "images": ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800"],
        "featured": false
    },
    {
        "category": "house",
        "code": "P-009",
        "title": "Hill Country Cottage",
        "price": 32000000,
        "currency": "LKR",
        "location": {
            "city": "Nuwara Eliya",
            "area": "Lake View",
            "district": "Nuwara Eliya"
        },
        "bedrooms": 3,
        "bathrooms": 2,
        "areaSize": 1800,
        "areaUnit": "sqft",
        "floors": 2,
        "listingType": "sale",
        "condition": "used",
        "status": "available",
        "description": "Picturesque cottage overlooking Gregory Lake. Teak floors, fireplace, and beautiful flower gardens. Perfect holiday home.",
        "features": ["Lake View", "Fireplace", "Garden", "Attic"],
        "images": ["https://images.unsplash.com/photo-1542718610-a1d656d1884c?auto=format&fit=crop&q=80&w=800"],
        "featured": false
    },
    {
        "category": "house",
        "code": "P-010",
        "title": "Modern Office Space",
        "price": 450000,
        "currency": "LKR",
        "location": {
            "city": "Colombo 02",
            "area": "Union Place",
            "district": "Colombo"
        },
        "bedrooms": 0,
        "bathrooms": 2,
        "areaSize": 2500,
        "areaUnit": "sqft",
        "floors": 5,
        "listingType": "rent",
        "condition": "new",
        "status": "available",
        "description": "Grade A office space in commercial hub. Central AC, backup generator, and basement parking included.",
        "features": ["Central AC", "Generator", "Lift", "Security"],
        "images": ["https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=800"],
        "featured": true
    },
    {
        "category": "land",
        "code": "L-001",
        "title": "Prime Residential Land in Kandy",
        "price": 12000000,
        "currency": "LKR",
        "location": {
            "city": "Kandy",
            "area": "Primrose Garden",
            "district": "Kandy"
        },
        "perches": 15,
        "listingType": "sale",
        "status": "available",
        "electricity": true,
        "water": true,
        "description": "A beautiful plot of residential land located in the peaceful Primrose Garden area of Kandy. Perfect for building your dream home with a panoramic view of the hills. Includes easy access to utilities.",
        "features": ["Hill View", "Gated Community", "Easy Access", "Clear Deeds"],
        "images": ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800"],
        "featured": true
    },
    {
        "category": "land",
        "code": "L-002",
        "title": "Commercial Land near Main Road",
        "price": 45000000,
        "currency": "LKR",
        "location": {
            "city": "Malabe",
            "area": "Pittugala",
            "district": "Colombo"
        },
        "perches": 20,
        "listingType": "sale",
        "status": "available",
        "electricity": true,
        "water": true,
        "description": "Ideally located commercial land in Malabe, just 50 meters from the main road. Perfect for office buildings, warehouses, or retail space. High growth area with excellent investment potential.",
        "features": ["Main Road Access", "High Visibility", "Level Ground"],
        "images": ["https://images.unsplash.com/photo-1599809275372-b40c7e9379d5?auto=format&fit=crop&q=80&w=800"],
        "featured": false
    }
];
